# aws:
#   access_key_id: 123
#   secret_access_key: 345

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
development:
  secret_key_base:
  action_mailer:
    username:
    password:
    email_from_address:

test:
  secret_key_base:
  action_mailer:
    username:
    password:
    email_from_address:

production:
  secret_key_base:
  action_mailer:
    username:
    password:
    email_from_address:
  sendgrid:
    api_key:
  cloudflare:
    account_id:
    access_key_id:
    secret_access_key:
    bucket:
